# Generated by Django 5.1.2 on 2024-11-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('curriculum', models.FileField(upload_to='Documentos/')),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255)),
                ('creation_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_services',
            fields=[
                ('category_services_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='paymenth_methods',
            fields=[
                ('paymenth_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='priorities',
            fields=[
                ('prority_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expire_date', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='vacant',
            fields=[
                ('vacant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('requirements', models.TextField(max_length=255)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField()),
            ],
        ),
    ]
