# Generated by Django 5.1.2 on 2024-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymenth_methods',
            fields=[
                ('paymenth_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
