# Generated by Django 5.1.2 on 2024-11-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymenth_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacant',
            fields=[
                ('vacant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('requirements', models.TextField(max_length=255)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField()),
            ],
        ),
    ]
