# Generated by Django 5.1.2 on 2024-11-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_stock', models.IntegerField()),
                ('available_stock', models.IntegerField()),
                ('reserved_stock', models.IntegerField()),
                ('damaged_stock', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
        ),
    ]
