# Generated by Django 5.1.2 on 2024-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vacant'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('curriculum', models.FileField(upload_to='Documentos/')),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
