# Generated by Django 5.1.2 on 2024-11-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs_positions',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('position_description', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areas')),
            ],
        ),
    ]
