# Generated by Django 5.1.2 on 2024-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.TextField()),
            ],
        ),
    ]
