# Generated by Django 5.1.2 on 2024-11-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_priorities'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_services',
            fields=[
                ('category_services_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
