# Generated by Django 5.1.2 on 2024-11-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_categories_products',
            fields=[
                ('sub_category_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
            ],
        ),
    ]
