# Generated by Django 5.1.2 on 2024-11-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sub_categories_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.TimeField()),
                ('sub_categories_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sub_categories_products')),
            ],
        ),
    ]
