# Generated by Django 5.1.2 on 2024-11-14 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_staff_events_staff_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects_services',
            fields=[
                ('project_services_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
        ),
    ]
