# Generated by Django 5.1.2 on 2024-11-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_staff_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='languages_clients',
            fields=[
                ('language_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.languages')),
            ],
        ),
    ]
