# Generated by Django 5.1.2 on 2024-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_proformas_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas_invoices',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
