# Generated by Django 5.1.2 on 2024-11-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_proformas_invoices_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidates_vacants',
            fields=[
                ('candidate_vacant_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
                ('vacant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacant')),
            ],
        ),
    ]
