# Generated by Django 5.1.2 on 2024-11-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_candidates_vacants'),
    ]

    operations = [
        migrations.CreateModel(
            name='proformas_invoices_services',
            fields=[
                ('proforma_invoice_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proformas_invoices')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
        ),
        migrations.CreateModel(
            name='proformas_invoices_staff',
            fields=[
                ('proforma_invoice_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proformas_invoices')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
        ),
    ]
