# Generated by Django 5.1.2 on 2024-11-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_proformas_invoices_services_proformas_invoices_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='sells_details',
            fields=[
                ('sell_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sells')),
            ],
        ),
    ]
