# Generated by Django 5.1.2 on 2024-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_sells_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas_invoices',
            name='taxes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
