# Generated by Django 5.1.2 on 2024-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_proformas_invoices_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas_invoices',
            name='quiantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sells',
            name='taxes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
