# Generated by Django 5.1.2 on 2024-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_proformas_invoices_quiantity_alter_sells_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
