# Generated by Django 5.1.2 on 2024-11-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_sells_discount_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
