# Generated by Django 5.1.2 on 2024-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_products_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells_details',
            name='comments',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
