# Generated by Django 5.1.2 on 2024-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_stock',
            field=models.IntegerField(blank=True),
        ),
    ]
