# Generated by Django 5.1.2 on 2024-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_inventory_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
