# Generated by Django 5.1.2 on 2024-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_inventory_available_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
