# Generated by Django 5.1.2 on 2024-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_inventory_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='ID',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
