# Generated by Django 5.1.2 on 2024-11-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_user_clients_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='user_id',
            new_name='user',
        ),
    ]
