# Generated by Django 5.1.2 on 2024-11-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_clients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
