# Generated by Django 5.1.2 on 2024-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_clients_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=2200),
        ),
        migrations.AddField(
            model_name='services',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=2200),
        ),
    ]
