# Generated by Django 5.1.2 on 2024-11-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_services_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='imagen_url',
            field=models.TextField(max_length=2000),
        ),
    ]
