# Generated by Django 5.1.2 on 2024-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_services_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imagen_url',
            field=models.TextField(blank=True, max_length=2200),
        ),
    ]
