# Generated by Django 5.1.4 on 2024-12-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_cita_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='fecha',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='direccion',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='hora',
            new_name='time',
        ),
    ]
