# Generated by Django 5.1.4 on 2024-12-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_fecha_cita_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='direction',
            new_name='address',
        ),
    ]
