# Generated by Django 5.1.4 on 2024-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rename_direction_cita_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='ending_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='starting_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='expire_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
