# Generated by Django 5.1.4 on 2024-12-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_events_ending_date_alter_events_starting_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='Date',
            new_name='date',
        ),
    ]
